name: Heukma git actions
on:
   # push:
   #    branches:
   #       - 'master'
   workflow_dispatch:
            
jobs:
   Heukma-Action:
      runs-on: ubuntu-latest
      steps:       
         - name: Uploader
           uses: binary-0/Automatic-Tistory-Uploader@Test_python_markdown_extension
           with:
              Accesstoken: "${{ secrets.BLOG_ACCESS_TOKEN }}"
              BlogName: "nmincho"
              GithubToken: "${{ secrets.GITHUB_TOKEN }}"
