name: Heukma git actions
on:
   workflow_dispatch:

            
jobs:
   Heukma-Action:
      runs-on: ubuntu-latest
      steps:         
         - name: Checkout
           uses: actions/checkout@v3
           with:
              sparse-checkout: |
                 .
                 test
                 scripts
         - name: List all long
           run: ls -al
         - name: Change file mode
           run: chmod +x ./scripts/world.sh
         - name: execute world.sh
           run: ./scripts/world.sh
