name: Heukma git actions
on:
   workflow_dispatch:

            
jobs:
   Heukma-Action:
      runs-on: ubuntu-latest
      steps:         
         - name: Checkout
           uses: actions/checkout@v3
           with:
              sparse-checkout: |
                 scripts
         - name: Change file mode
           run: chmod +x world.sh
         - name: execute world.sh
           run: ./world.sh
