name: Heukma git actions
on:
   workflow_dispatch:
      inputs:
         myName:
            description: "이름을 입력해주세요"
            required: true
            default: ''
jobs:
   runs-on: ubuntu-latest
   steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: .
      - name: List all long
        run: ls -al
