name: Heukma git actions
on:
   # push:
   #    branches:
   #       - 'master'
   workflow_dispatch:
      inputs:
         AccessToken:
            description: "Access token of your blog"
            required: true
            default: ''
            
jobs:
   Heukma-Action:
      runs-on: ubuntu-latest
      steps:         
         - name: Uploader
           uses: Heukma/my-first-repo@main
           with:
              Accesstoken: "${{ github.event.inputs.AccessToken }}"
              BlogName: "nmincho"
